fixup! net: usb: rtl8150: Fix frame padding
Fixes commit d4000407ca9b94779b86567198f74a3b34d3c2fc upstream.

The fix was based on commit 2f5281ba2a8feaf6f0aee93356f350855bb530fc
upstream.

/home/thomas/a21s/kernel/qcom/sm8250/drivers/net/usb/rtl8150.c:707:10: error: comparison of distinct pointer types ('typeof (skb->len) *' (aka 'unsigned int *') and 'typeof (60) *' (aka 'int *')) [-Werror,-Wcompare-distinct-pointer-types]
  707 |         count = max(skb->len, ETH_ZLEN);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~

Change-Id: If4a118c06c11ee66b80042534300158ec1f2039b